### ISSUE TITLE
Weird $def error in cmd-ride programs. (A little too much C in the forth?)

### ISSUE THREAD

**Issue by KETNAR** [fuzzball-muck/fuzzball-muf#44]
https://github.com/fuzzball-muck/fuzzball-muf/blob/69399c6bd877d8cfa4410952147ae54d30038cea/cmd-ride.muf#L491

This funky $def does not work as intended as far as the program it is contained in cares. (I tried to set ~prog as a ref and as a str, still no joy, ride-check just plain doesn't like it.) and it results in some pretty funktactular crashing problems. (including a 'see a crash every time you take an exit', until the /ride/ props are manually cleared or the program fixed.)

The workaround is to just old-school $def globalprop #1234 (the debref of the cmd-ride program which holds all of the various carry message props.)

Otherwise, program works flawlessly, save for this weird magical $def gumming up the works and triggering conga-line chaos and otherwise breaking the out of the box 'build-and-go' experience.

I'm.. not even sure muf $def can DO that ..? Can it? I'm sending the issue half just to find out.

**Comment by tanabi** [comment]
Looks like it would need to be a ref.  I think there's a better way to do this really, I can tihnk of a few methods off the top of my head that would be better.  For instance, registering what should be ~prop and using "$whatever" match instead of setting some random prop somewehre.

**Comment by wyld-sw** [comment]
I just learned that the version of the prop we have in starterdb is "~/prog" not "~prog" - so definitely one of those needs updating.

I'd be interested in doing something different eventually since this does seem a bit "hacky", but it's better than hardcoding the dbref (assuming it works).

I just loaded up an instance of starterdb and I seem to be able to go through exits with a rider with no problem, but there may be some expectation I'm missing.

As you know, the $def is intended to replace "globalprop" with the code that gets the dbref from the ~prog prop (as established in line 821 of the script).

I assume all you need to replicate this issue is two rooms, and exit between them, and a rider. What was the series of commands that led to the crash? I may have not tried that case.

I'd also be happy to join you on your MUCK to see firsthand if I can help.

**Comment by KETNAR** [comment]
Hmm, thats weird. But my install did go a little funky and cmd-ride and check-ride got separated by a few more dbrefs than i'd like. But that should not make a difference.

Otherwise, my install is straight off the git (as in, i started with minimal, not starterdb), I just had some other libs and cmds already in the way.

But mine definitely had ~prog and not ~/prog.

**Comment by KETNAR** [comment]
> I assume all you need to replicate this issue is two rooms, and exit between them, and a rider. What was the series of commands that led to the crash? I may have not tried that case.

This is correct, and exactly how I was testing it. I was using non-wiz users as well.

As for jumping into the muck, it's not on a public host anywhere at the moment. (bit of a pet project right now forcing myself to learn muf.)

I corrected the issue with the workaround I mentioned, but i can revert and try adding the / in there and see if that resolves it.

**Comment by KETNAR** [comment]
Confirmed, the switch from ~prog to ~/prog does in fact clear up the issue. A simple update to the git source should sort it out.

All that crash for one little slash. I could have sworn I tested that to no effect, but alas, here we are.

At least they say egg is good for the skin and completion. Sigh, this is what I get for mucking with this tired.. :]
